# Generated by Django 4.0.6 on 2022-08-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_ticket_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='link',
        ),
    ]
