# Generated by Django 4.0.6 on 2022-08-28 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_usertheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTheme',
        ),
    ]
