# Generated by Django 4.0.6 on 2022-09-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_askreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskReview',
        ),
    ]
