# Generated by Django 4.0.6 on 2022-09-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_delete_askreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review_done',
            field=models.BooleanField(default=False),
        ),
    ]
