# Generated by Django 4.0.6 on 2022-08-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('cyborg', 'cyborg'), ('cerulean', 'cerulean'), ('quartz', 'quartz'), ('lumen', 'lumen'), ('simplex', 'simplex'), ('sketchy', 'sketchy')], default='cyborg', max_length=10)),
            ],
        ),
    ]
