# Generated by Django 4.0.6 on 2022-08-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userfollows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='theme',
            field=models.CharField(choices=[('cyborg', 'cyborg'), ('cerulean', 'cerulean'), ('lux', 'lux'), ('lumen', 'lumen'), ('simplex', 'simplex'), ('sketchy', 'sketchy')], default='cyborg', max_length=10),
        ),
    ]
