# Generated by Django 4.0.6 on 2022-08-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usertheme_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertheme',
            name='theme',
            field=models.CharField(choices=[('cyborg', 'cyborg'), ('cerulean', 'cerulean'), ('lux', 'lux'), ('lumen', 'lumen'), ('simplex', 'simplex'), ('morph', 'morph'), ('minty', 'minty'), ('slate', 'slate'), ('vapor', 'vapor'), ('zephyr', 'zephyr')], default='cyborg', max_length=10),
        ),
    ]
